name: Release

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Version
      id: version
      run: |
        CALVER="$(date -u +%Y.%-m.%-d).${GITHUB_RUN_NUMBER}"
        TAGS="${CALVER}"
        echo ::set-output name=tags::${TAGS}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build with Maven Wrapper
      run: |
        ./mvnw -DnewVersion="${{ steps.version.outputs.tags }}" -DgenerateBackupPoms=false --batch-mode versions:set
        ./mvnw -B package
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
    - name: Build Docker image and push it to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/latest
          docker.pkg.github.com/${{ github.repository }}/${{ steps.version.outputs.tags }}
    - name: Create Release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.tags }}
        release_name: Release ${{ steps.version.outputs.tags }}
        draft: false
        prerelease: false
        body: "test relelelealse"
