name: Release

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Version
      id: version
      run: |
        CALVER=$(date +%Y.%-m.%-d)
        TAGS="latest,${CALVER}"
        echo ::set-output name=tags::${TAGS}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven Wrapper
      run: |
        ./mvnw -DnewVersion="${{ steps.version.outputs.tags }}" -DgenerateBackupPoms=false --batch-mode versions:set
        ./mvnw -B verify
    - name: Build Docker image and push it to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/prometheus-jdbc-exporter
        tags: ${{ steps.version.outputs.tags }}
        tag_with_ref: true
